create database cineFlix;
create table admin (id integer not null, password varchar(255), primary key (id)) engine=InnoDB;
create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
create table invoice (trans_id varchar(255) not null, price integer not null, quantity integer not null, time time, user_id integer not null, user_name varchar(255), primary key (trans_id)) engine=InnoDB;
create table movie (movie_id integer not null, censor varchar(255), genre varchar(255), image_url varchar(255), language varchar(255), movie_name varchar(255), movie_synopsis varchar(255), release_date date, primary key (movie_id)) engine=InnoDB;
create table movie_theatre (movies_movie_id integer not null, theatre_theatre_id integer not null, primary key (movies_movie_id, theatre_theatre_id)) engine=InnoDB;
create table screen (id integer not null, budget_rows integer not null, screen_name varchar(255), total_columns integer not null, total_rows integer not null, theatre_theatre_id integer, primary key (id)) engine=InnoDB;
create table show_table (show_id integer not null, movie_name varchar(255), show_date date, show_time time, screen_id integer, primary key (show_id)) engine=InnoDB;
create table theatre (theatre_id integer not null, password varchar(255), theatre_address varchar(255), theatre_name varchar(255), primary key (theatre_id)) engine=InnoDB;
create table ticket (ticket_id integer not null, movie_name varchar(255), no_of_seats integer not null, screen_name varchar(255), seat_numbers varchar(255), show_date date, show_timing time, theatre_name varchar(255), user_user_id integer, primary key (ticket_id)) engine=InnoDB;
create table user (user_id integer not null auto_increment, address varchar(255), email varchar(255), name varchar(255), number varchar(255), password varchar(255), primary key (user_id)) engine=InnoDB;
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user add constraint UK_32852vmffyhhg5ov56amkcx7s unique (number);
alter table movie_theatre add constraint FKjxalnbn4qm6rna742rprs8jr3 foreign key (theatre_theatre_id) references theatre (theatre_id);
alter table movie_theatre add constraint FKr3ry7vrryne10j7bc8m6u0g42 foreign key (movies_movie_id) references movie (movie_id);
alter table screen add constraint FKscfiy5yupbso5u8fmptrlgy16 foreign key (theatre_theatre_id) references theatre (theatre_id);
alter table show_table add constraint FKkisp3jkoxjyef53ta3hoteyvy foreign key (screen_id) references screen (id);
alter table ticket add constraint FK8nvar4k6awxj2y81vwyc1blff foreign key (user_user_id) references user (user_id);
insert into admin values(1234,"aaaa");
insert into theatre values(1234,"aaaa","","");